# ~/.tmuxinator/summer_bot.yml

name: summer_bot
root: .

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: export ROS_IP="10.0.0.145" ; 

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specitifes (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: tmux -CC attach -t summer_bot

windows:
  - win1:
      layout: tiled
      panes:
        - cowsay "roscore" ; export ROS_IP="10.0.0.145" ; roscore
        - cowsay "IMU Raw data publisher" ; export ROS_IP="10.0.0.145" ; sleep 10 ; python imu_raw.py
        - cowsay "IMU fusion node" ; export ROS_IP="10.0.0.145" ; sleep 10 ; rosrun imu_filter_madgwick imu_filter_node
        - cowsay "teleop receiver node" ; export ROS_IP="10.0.0.145" ; sleep 10 ; python robot.py
        - cowsay "RP Lidar node" ; export ROS_IP="10.0.0.145" ; sleep 10 ; roslaunch rplidar_ros view_rplidar.launch 
        - htop
  
